// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20231126004447_heroeq")]
    partial class heroeq
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Classes.Models.Game.Hero.DBHero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<int?>("ArmorId")
                        .HasColumnType("int");

                    b.Property<int>("Atack")
                        .HasColumnType("int");

                    b.Property<int?>("BootsId")
                        .HasColumnType("int");

                    b.Property<int>("CriticalChance")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Dead")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GlovesId")
                        .HasColumnType("int");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<int>("HealthPoints")
                        .HasColumnType("int");

                    b.Property<int?>("HelmetId")
                        .HasColumnType("int");

                    b.Property<bool>("InGame")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MagicArmor")
                        .HasColumnType("int");

                    b.Property<int>("MagicAtack")
                        .HasColumnType("int");

                    b.Property<int>("Mana")
                        .HasColumnType("int");

                    b.Property<int>("MapId")
                        .HasColumnType("int");

                    b.Property<int>("MaxHealthPoints")
                        .HasColumnType("int");

                    b.Property<int>("MaxMana")
                        .HasColumnType("int");

                    b.Property<int>("MaxStamina")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("NecklaceId")
                        .HasColumnType("int");

                    b.Property<int>("Profession")
                        .HasColumnType("int");

                    b.Property<int?>("RingId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryWeaponId")
                        .HasColumnType("int");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<string>("SpriteURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stamina")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("WeaponId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArmorId");

                    b.HasIndex("BootsId");

                    b.HasIndex("GlovesId");

                    b.HasIndex("HelmetId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("NecklaceId");

                    b.HasIndex("RingId");

                    b.HasIndex("SecondaryWeaponId");

                    b.HasIndex("UserId");

                    b.HasIndex("WeaponId");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("Classes.Models.Game.Hero.DBHeroEquipment", b =>
                {
                    b.Property<int>("HeroId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.HasKey("HeroId", "OrderId");

                    b.ToTable("HeroesEquipments");
                });

            modelBuilder.Entity("Classes.Models.Game.Item.Armor.DBArmor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<int>("HealthPoints")
                        .HasColumnType("int");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MagicArmor")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Profession")
                        .HasColumnType("int");

                    b.Property<string>("SpriteURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Armors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agility = 5,
                            Armor = 30,
                            HealthPoints = 5,
                            ItemType = 2,
                            Level = 1,
                            MagicArmor = 0,
                            Name = "Red Caftan",
                            Price = 20,
                            Profession = 0,
                            SpriteURL = "armorWarrior0.gif",
                            Weight = 5
                        },
                        new
                        {
                            Id = 2,
                            Agility = 10,
                            Armor = 20,
                            HealthPoints = 0,
                            ItemType = 2,
                            Level = 1,
                            MagicArmor = 0,
                            Name = "Leather Armor",
                            Price = 20,
                            Profession = 1,
                            SpriteURL = "armorHunter0.gif",
                            Weight = 3
                        },
                        new
                        {
                            Id = 3,
                            Agility = 5,
                            Armor = 5,
                            HealthPoints = 20,
                            ItemType = 2,
                            Level = 1,
                            MagicArmor = 15,
                            Name = "Wanderer's Coat",
                            Price = 20,
                            Profession = 2,
                            SpriteURL = "armorMage0.gif",
                            Weight = 3
                        },
                        new
                        {
                            Id = 4,
                            Agility = 0,
                            Armor = 10,
                            HealthPoints = 10,
                            ItemType = 2,
                            Level = 1,
                            MagicArmor = 10,
                            Name = "Incomplete Armor",
                            Price = 20,
                            Profession = 3,
                            SpriteURL = "armorPaladin0.gif",
                            Weight = 7
                        },
                        new
                        {
                            Id = 5,
                            Agility = 0,
                            Armor = 55,
                            HealthPoints = 15,
                            ItemType = 2,
                            Level = 10,
                            MagicArmor = 0,
                            Name = "Wanderer's Chainmail",
                            Price = 50,
                            Profession = 0,
                            SpriteURL = "armorWarrior10.gif",
                            Weight = 10
                        },
                        new
                        {
                            Id = 6,
                            Agility = 25,
                            Armor = 25,
                            HealthPoints = 5,
                            ItemType = 2,
                            Level = 10,
                            MagicArmor = 0,
                            Name = "Tunic Of Agility",
                            Price = 35,
                            Profession = 1,
                            SpriteURL = "armorHunter10.gif",
                            Weight = 5
                        },
                        new
                        {
                            Id = 7,
                            Agility = 5,
                            Armor = 15,
                            HealthPoints = 20,
                            ItemType = 2,
                            Level = 10,
                            MagicArmor = 35,
                            Name = "Novice's Coat",
                            Price = 30,
                            Profession = 2,
                            SpriteURL = "armorMage10.gif",
                            Weight = 5
                        },
                        new
                        {
                            Id = 8,
                            Agility = 0,
                            Armor = 25,
                            HealthPoints = 10,
                            ItemType = 2,
                            Level = 10,
                            MagicArmor = 25,
                            Name = "Steel Breastplate",
                            Price = 55,
                            Profession = 3,
                            SpriteURL = "armorPaladin10.gif",
                            Weight = 15
                        },
                        new
                        {
                            Id = 9,
                            Agility = 5,
                            Armor = 100,
                            HealthPoints = 30,
                            ItemType = 2,
                            Level = 20,
                            MagicArmor = 0,
                            Name = "Reinforced Wanderer's Chainmail",
                            Price = 250,
                            Profession = 0,
                            SpriteURL = "armorWarrior20.gif",
                            Weight = 15
                        },
                        new
                        {
                            Id = 10,
                            Agility = 15,
                            Armor = 65,
                            HealthPoints = 35,
                            ItemType = 2,
                            Level = 20,
                            MagicArmor = 0,
                            Name = "Hunter's Tunic",
                            Price = 150,
                            Profession = 1,
                            SpriteURL = "armorHunter20.gif",
                            Weight = 10
                        },
                        new
                        {
                            Id = 11,
                            Agility = 5,
                            Armor = 30,
                            HealthPoints = 50,
                            ItemType = 2,
                            Level = 20,
                            MagicArmor = 95,
                            Name = "Thinker's Coat",
                            Price = 200,
                            Profession = 2,
                            SpriteURL = "armorMage20.gif",
                            Weight = 8
                        },
                        new
                        {
                            Id = 12,
                            Agility = 0,
                            Armor = 75,
                            HealthPoints = 50,
                            ItemType = 2,
                            Level = 20,
                            MagicArmor = 75,
                            Name = "Guardian Armor",
                            Price = 350,
                            Profession = 3,
                            SpriteURL = "armorPaladin20.gif",
                            Weight = 20
                        });
                });

            modelBuilder.Entity("Classes.Models.Game.Item.Boots.DBBoots", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<int>("HealthPoints")
                        .HasColumnType("int");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MagicArmor")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Profession")
                        .HasColumnType("int");

                    b.Property<string>("SpriteURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Boots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agility = 5,
                            Armor = 5,
                            HealthPoints = 0,
                            ItemType = 4,
                            Level = 1,
                            MagicArmor = 0,
                            Name = "Chainmail Boots",
                            Price = 5,
                            Profession = 0,
                            SpriteURL = "bootsWarrior0.gif",
                            Weight = 2
                        },
                        new
                        {
                            Id = 2,
                            Agility = 5,
                            Armor = 1,
                            HealthPoints = 5,
                            ItemType = 4,
                            Level = 1,
                            MagicArmor = 0,
                            Name = "Sheepskin Boots",
                            Price = 1,
                            Profession = 1,
                            SpriteURL = "bootsHunter0.gif",
                            Weight = 1
                        },
                        new
                        {
                            Id = 3,
                            Agility = 2,
                            Armor = 1,
                            HealthPoints = 3,
                            ItemType = 4,
                            Level = 1,
                            MagicArmor = 5,
                            Name = "Leather Slippers",
                            Price = 2,
                            Profession = 2,
                            SpriteURL = "bootsMage0.gif",
                            Weight = 1
                        },
                        new
                        {
                            Id = 4,
                            Agility = 0,
                            Armor = 15,
                            HealthPoints = 0,
                            ItemType = 4,
                            Level = 1,
                            MagicArmor = 5,
                            Name = "Steel Boots",
                            Price = 10,
                            Profession = 3,
                            SpriteURL = "bootsPaladin0.gif",
                            Weight = 3
                        });
                });

            modelBuilder.Entity("Classes.Models.Game.Item.Consumables.DBConsumables", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<int>("HealthPoints")
                        .HasColumnType("int");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<int>("Mana")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("SpriteURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stamina")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Consumables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gold = 0,
                            HealthPoints = 10,
                            ItemType = 8,
                            Mana = 0,
                            Name = "Small Health Potion",
                            Price = 20,
                            SpriteURL = "potionHealthSmall.gif",
                            Stamina = 0
                        },
                        new
                        {
                            Id = 2,
                            Gold = 0,
                            HealthPoints = 0,
                            ItemType = 8,
                            Mana = 0,
                            Name = "Small Stamina Potion",
                            Price = 50,
                            SpriteURL = "potionStaminaSmall.gif",
                            Stamina = 10
                        },
                        new
                        {
                            Id = 3,
                            Gold = 0,
                            HealthPoints = 0,
                            ItemType = 8,
                            Mana = 10,
                            Name = "Small Mana Potion",
                            Price = 50,
                            SpriteURL = "potionManaSmall.gif",
                            Stamina = 0
                        },
                        new
                        {
                            Id = 4,
                            Gold = 0,
                            HealthPoints = 30,
                            ItemType = 8,
                            Mana = 0,
                            Name = "Medium Health Potion",
                            Price = 100,
                            SpriteURL = "potionHealthMedium.gif",
                            Stamina = 0
                        },
                        new
                        {
                            Id = 5,
                            Gold = 0,
                            HealthPoints = 0,
                            ItemType = 8,
                            Mana = 0,
                            Name = "Medium Stamina Potion",
                            Price = 200,
                            SpriteURL = "potionStaminaMedium.gif",
                            Stamina = 30
                        },
                        new
                        {
                            Id = 6,
                            Gold = 0,
                            HealthPoints = 0,
                            ItemType = 8,
                            Mana = 30,
                            Name = "Medium Mana Potion",
                            Price = 200,
                            SpriteURL = "potionManaMedium.gif",
                            Stamina = 0
                        },
                        new
                        {
                            Id = 7,
                            Gold = 0,
                            HealthPoints = 100,
                            ItemType = 8,
                            Mana = 0,
                            Name = "Large Health Potion",
                            Price = 1000,
                            SpriteURL = "potionHealthLarge.gif",
                            Stamina = 0
                        },
                        new
                        {
                            Id = 8,
                            Gold = 0,
                            HealthPoints = 0,
                            ItemType = 8,
                            Mana = 0,
                            Name = "Large Stamina Potion",
                            Price = 2000,
                            SpriteURL = "potionStaminaLarge.gif",
                            Stamina = 100
                        },
                        new
                        {
                            Id = 9,
                            Gold = 0,
                            HealthPoints = 0,
                            ItemType = 8,
                            Mana = 100,
                            Name = "Large Mana Potion",
                            Price = 2000,
                            SpriteURL = "potionManaLarge.gif",
                            Stamina = 0
                        },
                        new
                        {
                            Id = 10,
                            Gold = 0,
                            HealthPoints = 2,
                            ItemType = 8,
                            Mana = 0,
                            Name = "Apple",
                            Price = 3,
                            SpriteURL = "apple.gif",
                            Stamina = 0
                        },
                        new
                        {
                            Id = 11,
                            Gold = 0,
                            HealthPoints = 5,
                            ItemType = 8,
                            Mana = 0,
                            Name = "Meat",
                            Price = 8,
                            SpriteURL = "meat.gif",
                            Stamina = 0
                        },
                        new
                        {
                            Id = 12,
                            Gold = 0,
                            HealthPoints = -10,
                            ItemType = 8,
                            Mana = 5,
                            Name = "Night Mashroom",
                            Price = 5,
                            SpriteURL = "nightMashroom.gif",
                            Stamina = 5
                        },
                        new
                        {
                            Id = 13,
                            Gold = 15,
                            HealthPoints = 0,
                            ItemType = 8,
                            Mana = 0,
                            Name = "Pile Of Coins",
                            Price = 0,
                            SpriteURL = "pileOfCoins.gif",
                            Stamina = 0
                        });
                });

            modelBuilder.Entity("Classes.Models.Game.Item.Gloves.DBGloves", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<int>("HealthPoints")
                        .HasColumnType("int");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MagicArmor")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Profession")
                        .HasColumnType("int");

                    b.Property<string>("SpriteURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Gloves");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agility = 0,
                            Armor = 10,
                            HealthPoints = 5,
                            ItemType = 5,
                            Level = 1,
                            MagicArmor = 0,
                            Name = "Steel Bracelets",
                            Price = 5,
                            Profession = 0,
                            SpriteURL = "glovesWarrior0.gif",
                            Weight = 4
                        },
                        new
                        {
                            Id = 2,
                            Agility = 5,
                            Armor = 5,
                            HealthPoints = 5,
                            ItemType = 5,
                            Level = 1,
                            MagicArmor = 0,
                            Name = "Leather Gloves",
                            Price = 2,
                            Profession = 1,
                            SpriteURL = "glovesHunter0.gif",
                            Weight = 2
                        },
                        new
                        {
                            Id = 3,
                            Agility = 0,
                            Armor = 2,
                            HealthPoints = 5,
                            ItemType = 5,
                            Level = 1,
                            MagicArmor = 8,
                            Name = "Black Gloves",
                            Price = 3,
                            Profession = 2,
                            SpriteURL = "glovesMage0.gif",
                            Weight = 2
                        },
                        new
                        {
                            Id = 4,
                            Agility = -2,
                            Armor = 10,
                            HealthPoints = 0,
                            ItemType = 5,
                            Level = 1,
                            MagicArmor = 5,
                            Name = "Iron Paws",
                            Price = 5,
                            Profession = 3,
                            SpriteURL = "glovesPaladin0.gif",
                            Weight = 4
                        });
                });

            modelBuilder.Entity("Classes.Models.Game.Item.Helmet.DBHelmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<int>("HealthPoints")
                        .HasColumnType("int");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MagicArmor")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Profession")
                        .HasColumnType("int");

                    b.Property<string>("SpriteURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Helmets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agility = 0,
                            Armor = 5,
                            HealthPoints = 0,
                            ItemType = 3,
                            Level = 1,
                            MagicArmor = 0,
                            Name = "Copper Helmet",
                            Price = 10,
                            Profession = 0,
                            SpriteURL = "helmetWarrior0.gif",
                            Weight = 3
                        },
                        new
                        {
                            Id = 2,
                            Agility = 0,
                            Armor = 1,
                            HealthPoints = 5,
                            ItemType = 3,
                            Level = 1,
                            MagicArmor = 0,
                            Name = "Wanderer's Hat",
                            Price = 2,
                            Profession = 1,
                            SpriteURL = "helmetHunter0.gif",
                            Weight = 1
                        },
                        new
                        {
                            Id = 3,
                            Agility = 0,
                            Armor = 1,
                            HealthPoints = 10,
                            ItemType = 3,
                            Level = 1,
                            MagicArmor = 10,
                            Name = "Magician's Hat",
                            Price = 5,
                            Profession = 2,
                            SpriteURL = "helmetMage0.gif",
                            Weight = 2
                        },
                        new
                        {
                            Id = 4,
                            Agility = 0,
                            Armor = 5,
                            HealthPoints = 0,
                            ItemType = 3,
                            Level = 1,
                            MagicArmor = 10,
                            Name = "Zinc Helmet",
                            Price = 10,
                            Profession = 3,
                            SpriteURL = "helmetPaladin0.gif",
                            Weight = 3
                        },
                        new
                        {
                            Id = 5,
                            Agility = -5,
                            Armor = 40,
                            HealthPoints = 15,
                            ItemType = 3,
                            Level = 10,
                            MagicArmor = 0,
                            Name = "Viking Helmet",
                            Price = 30,
                            Profession = 0,
                            SpriteURL = "helmetWarrior10.gif",
                            Weight = 7
                        },
                        new
                        {
                            Id = 6,
                            Agility = 5,
                            Armor = 10,
                            HealthPoints = 10,
                            ItemType = 3,
                            Level = 10,
                            MagicArmor = 0,
                            Name = "Elf Hat",
                            Price = 15,
                            Profession = 1,
                            SpriteURL = "helmetHunter10.gif",
                            Weight = 2
                        },
                        new
                        {
                            Id = 7,
                            Agility = 0,
                            Armor = 1,
                            HealthPoints = 30,
                            ItemType = 3,
                            Level = 10,
                            MagicArmor = 10,
                            Name = "Student Cap",
                            Price = 5,
                            Profession = 2,
                            SpriteURL = "helmetMage10.gif",
                            Weight = 1
                        },
                        new
                        {
                            Id = 8,
                            Agility = 0,
                            Armor = 25,
                            HealthPoints = 5,
                            ItemType = 3,
                            Level = 10,
                            MagicArmor = 15,
                            Name = "Steel Helmet",
                            Price = 10,
                            Profession = 3,
                            SpriteURL = "helmetPaladin10.gif",
                            Weight = 6
                        },
                        new
                        {
                            Id = 9,
                            Agility = 5,
                            Armor = 30,
                            HealthPoints = 15,
                            ItemType = 3,
                            Level = 20,
                            MagicArmor = 0,
                            Name = "Battle Helmet",
                            Price = 100,
                            Profession = 0,
                            SpriteURL = "helmetWarrior20.gif",
                            Weight = 6
                        },
                        new
                        {
                            Id = 10,
                            Agility = 25,
                            Armor = 10,
                            HealthPoints = 5,
                            ItemType = 3,
                            Level = 20,
                            MagicArmor = 0,
                            Name = "Agility Hood",
                            Price = 40,
                            Profession = 1,
                            SpriteURL = "helmetHunter20.gif",
                            Weight = 2
                        },
                        new
                        {
                            Id = 11,
                            Agility = 5,
                            Armor = 15,
                            HealthPoints = 15,
                            ItemType = 3,
                            Level = 20,
                            MagicArmor = 15,
                            Name = "Helmet of Versatility",
                            Price = 200,
                            Profession = 2,
                            SpriteURL = "helmetMage20.gif",
                            Weight = 4
                        },
                        new
                        {
                            Id = 12,
                            Agility = 0,
                            Armor = 30,
                            HealthPoints = 10,
                            ItemType = 3,
                            Level = 20,
                            MagicArmor = 25,
                            Name = "Gilded Helmet",
                            Price = 100,
                            Profession = 3,
                            SpriteURL = "helmetPaladin20.gif",
                            Weight = 6
                        },
                        new
                        {
                            Id = 13,
                            Agility = 0,
                            Armor = 100,
                            HealthPoints = 0,
                            ItemType = 3,
                            Level = 30,
                            MagicArmor = 0,
                            Name = "Tournament Visor",
                            Price = 250,
                            Profession = 0,
                            SpriteURL = "helmetWarrior30.gif",
                            Weight = 7
                        },
                        new
                        {
                            Id = 14,
                            Agility = 5,
                            Armor = 65,
                            HealthPoints = 30,
                            ItemType = 3,
                            Level = 30,
                            MagicArmor = 0,
                            Name = "Bear Hat",
                            Price = 175,
                            Profession = 1,
                            SpriteURL = "helmetHunter30.gif",
                            Weight = 3
                        },
                        new
                        {
                            Id = 15,
                            Agility = 10,
                            Armor = 50,
                            HealthPoints = 40,
                            ItemType = 3,
                            Level = 30,
                            MagicArmor = 50,
                            Name = "Magical Hat Of The Crimson Avenger",
                            Price = 450,
                            Profession = 2,
                            SpriteURL = "helmetMage30.gif",
                            Weight = 2
                        },
                        new
                        {
                            Id = 16,
                            Agility = 0,
                            Armor = 85,
                            HealthPoints = 35,
                            ItemType = 3,
                            Level = 30,
                            MagicArmor = 45,
                            Name = "Helmet Of The Order",
                            Price = 300,
                            Profession = 3,
                            SpriteURL = "helmetPaladin30.gif",
                            Weight = 5
                        });
                });

            modelBuilder.Entity("Classes.Models.Game.Item.Necklace.DBNecklace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CriticalChance")
                        .HasColumnType("int");

                    b.Property<int>("HealthPoints")
                        .HasColumnType("int");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Mana")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("SpriteURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stamina")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Necklaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CriticalChance = 5,
                            HealthPoints = 0,
                            ItemType = 6,
                            Level = 1,
                            Mana = 0,
                            Name = "Father's Necklace",
                            Price = 10,
                            SpriteURL = "necklace0.gif",
                            Stamina = 20,
                            Weight = 1
                        },
                        new
                        {
                            Id = 2,
                            CriticalChance = 0,
                            HealthPoints = 0,
                            ItemType = 6,
                            Level = 10,
                            Mana = 40,
                            Name = "Necklace of Magic",
                            Price = 20,
                            SpriteURL = "necklace10.gif",
                            Stamina = 0,
                            Weight = 3
                        },
                        new
                        {
                            Id = 3,
                            CriticalChance = 5,
                            HealthPoints = 0,
                            ItemType = 6,
                            Level = 20,
                            Mana = 10,
                            Name = "Necklace of Fortune",
                            Price = 200,
                            SpriteURL = "necklace20.gif",
                            Stamina = 10,
                            Weight = 2
                        });
                });

            modelBuilder.Entity("Classes.Models.Game.Item.Neutral.DBNeutral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("SpriteURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Neutrals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            ItemType = 9,
                            Name = "Feather",
                            Price = 1,
                            SpriteURL = "feather.gif"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            ItemType = 9,
                            Name = "Boar Leather",
                            Price = 25,
                            SpriteURL = "boarLeather.gif"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            ItemType = 9,
                            Name = "Boar Tusk",
                            Price = 10,
                            SpriteURL = "boarTusk.gif"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            ItemType = 9,
                            Name = "Boar Tail",
                            Price = 5,
                            SpriteURL = "boarTail.gif"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            ItemType = 9,
                            Name = "Wolf Tusk",
                            Price = 15,
                            SpriteURL = "wolfTusk.gif"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Strong poison, some craftsmen may be interested in it.",
                            ItemType = 9,
                            Name = "Spider Poison",
                            Price = 50,
                            SpriteURL = "spiderPoison.gif"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Wonder if it can be useful for something?",
                            ItemType = 9,
                            Name = "Powder",
                            Price = 5,
                            SpriteURL = "powder.gif"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Rare expensive stone.",
                            ItemType = 9,
                            Name = "Jasper",
                            Price = 150,
                            SpriteURL = "jasper.gif"
                        },
                        new
                        {
                            Id = 9,
                            Description = "",
                            ItemType = 9,
                            Name = "Cloth",
                            Price = 5,
                            SpriteURL = "cloth.gif"
                        },
                        new
                        {
                            Id = 10,
                            Description = "",
                            ItemType = 9,
                            Name = "Wood",
                            Price = 100,
                            SpriteURL = "wood.gif"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Raw material.",
                            ItemType = 9,
                            Name = "Iron Nuggets",
                            Price = 200,
                            SpriteURL = "ironNuggets.gif"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Useful in crafts.",
                            ItemType = 9,
                            Name = "Iron Ingot",
                            Price = 1000,
                            SpriteURL = "ironIngot.gif"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Precious item.",
                            ItemType = 9,
                            Name = "Blue Crystal",
                            Price = 350,
                            SpriteURL = "blueCrystal.gif"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Wonder who it belonged to?",
                            ItemType = 9,
                            Name = "Trinket",
                            Price = 500,
                            SpriteURL = "trinket.gif"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Wonder what's inside?",
                            ItemType = 9,
                            Name = "Shell",
                            Price = 100,
                            SpriteURL = "shell.gif"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Precious find in one of the shells.",
                            ItemType = 9,
                            Name = "Pearl",
                            Price = 2500,
                            SpriteURL = "pearl.gif"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Precious find in one of the shells. Legend has it that the red color of the pearl comes from the blood of the king murdered by his subordinates.",
                            ItemType = 9,
                            Name = "Blood Pearl",
                            Price = 5000,
                            SpriteURL = "bloodPearl.gif"
                        });
                });

            modelBuilder.Entity("Classes.Models.Game.Item.QuestItem.DBQuestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpriteURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("QuestItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The alchemist's lost book.",
                            ItemType = 10,
                            Name = "Alchemist's Book",
                            SpriteURL = "alchemistBook.gif"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            ItemType = 10,
                            Name = "Crystal",
                            SpriteURL = "crystal.gif"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Will you find its destiny?",
                            ItemType = 10,
                            Name = "Mysterious Key",
                            SpriteURL = "key0.gif"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Allows you to enter the catacombs.",
                            ItemType = 10,
                            Name = "Key To Catacombs",
                            SpriteURL = "key1.gif"
                        },
                        new
                        {
                            Id = 5,
                            Description = "The healer's lost necklace.",
                            ItemType = 10,
                            Name = "Healer's Necklace",
                            SpriteURL = "healerNecklace.gif"
                        });
                });

            modelBuilder.Entity("Classes.Models.Game.Item.Ring.DBRing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CriticalChance")
                        .HasColumnType("int");

                    b.Property<int>("HealthPoints")
                        .HasColumnType("int");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Mana")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("SpriteURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stamina")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CriticalChance = 0,
                            HealthPoints = 100,
                            ItemType = 7,
                            Level = 1,
                            Mana = 10,
                            Name = "Father's Ring",
                            Price = 5,
                            SpriteURL = "ring0.gif",
                            Stamina = 5,
                            Weight = 1
                        },
                        new
                        {
                            Id = 2,
                            CriticalChance = 0,
                            HealthPoints = 200,
                            ItemType = 7,
                            Level = 10,
                            Mana = 0,
                            Name = "Health Ring",
                            Price = 15,
                            SpriteURL = "ring10.gif",
                            Stamina = 10,
                            Weight = 2
                        },
                        new
                        {
                            Id = 3,
                            CriticalChance = 10,
                            HealthPoints = 50,
                            ItemType = 7,
                            Level = 20,
                            Mana = 0,
                            Name = "Critical Ring",
                            Price = 40,
                            SpriteURL = "ring20.gif",
                            Stamina = 0,
                            Weight = 2
                        });
                });

            modelBuilder.Entity("Classes.Models.Game.Item.SecondaryWeapon.DBSecondaryWeapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<int>("Atack")
                        .HasColumnType("int");

                    b.Property<int>("CriticalChance")
                        .HasColumnType("int");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MagicArmor")
                        .HasColumnType("int");

                    b.Property<int>("MagicAtack")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Profession")
                        .HasColumnType("int");

                    b.Property<string>("SpriteURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SecondaryWeapons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Armor = 20,
                            Atack = 0,
                            CriticalChance = 0,
                            ItemType = 1,
                            Level = 1,
                            MagicArmor = 0,
                            MagicAtack = 0,
                            Name = "Round Wooden Shield",
                            Price = 10,
                            Profession = 0,
                            SpriteURL = "secondaryWarrior0.gif",
                            Weight = 5
                        },
                        new
                        {
                            Id = 2,
                            Armor = 0,
                            Atack = 5,
                            CriticalChance = 0,
                            ItemType = 1,
                            Level = 1,
                            MagicArmor = 0,
                            MagicAtack = 0,
                            Name = "Arrow",
                            Price = 1,
                            Profession = 1,
                            SpriteURL = "secondaryHunter0.gif",
                            Weight = 1
                        },
                        new
                        {
                            Id = 3,
                            Armor = 0,
                            Atack = 0,
                            CriticalChance = 3,
                            ItemType = 1,
                            Level = 1,
                            MagicArmor = 0,
                            MagicAtack = 0,
                            Name = "School Spell Book",
                            Price = 5,
                            Profession = 2,
                            SpriteURL = "secondaryMage0.gif",
                            Weight = 2
                        },
                        new
                        {
                            Id = 4,
                            Armor = 10,
                            Atack = 0,
                            CriticalChance = 0,
                            ItemType = 1,
                            Level = 1,
                            MagicArmor = 5,
                            MagicAtack = 0,
                            Name = "Beginner's Shield",
                            Price = 10,
                            Profession = 3,
                            SpriteURL = "secondaryPaladin0.gif",
                            Weight = 5
                        },
                        new
                        {
                            Id = 5,
                            Armor = 40,
                            Atack = 0,
                            CriticalChance = 2,
                            ItemType = 1,
                            Level = 10,
                            MagicArmor = 0,
                            MagicAtack = 0,
                            Name = "Knight's Shield",
                            Price = 20,
                            Profession = 0,
                            SpriteURL = "secondaryWarrior10.gif",
                            Weight = 5
                        },
                        new
                        {
                            Id = 6,
                            Armor = 0,
                            Atack = 10,
                            CriticalChance = 5,
                            ItemType = 1,
                            Level = 10,
                            MagicArmor = 0,
                            MagicAtack = 0,
                            Name = "Fire Arrow",
                            Price = 2,
                            Profession = 1,
                            SpriteURL = "secondaryHunter10.gif",
                            Weight = 1
                        },
                        new
                        {
                            Id = 7,
                            Armor = 0,
                            Atack = 0,
                            CriticalChance = 7,
                            ItemType = 1,
                            Level = 10,
                            MagicArmor = 0,
                            MagicAtack = 5,
                            Name = "Book Of Spells",
                            Price = 10,
                            Profession = 2,
                            SpriteURL = "secondaryMage10.gif",
                            Weight = 2
                        },
                        new
                        {
                            Id = 8,
                            Armor = 15,
                            Atack = 0,
                            CriticalChance = 2,
                            ItemType = 1,
                            Level = 10,
                            MagicArmor = 15,
                            MagicAtack = 0,
                            Name = "Friar's Shield",
                            Price = 25,
                            Profession = 3,
                            SpriteURL = "secondaryPaladin10.gif",
                            Weight = 5
                        },
                        new
                        {
                            Id = 9,
                            Armor = 65,
                            Atack = 0,
                            CriticalChance = 5,
                            ItemType = 1,
                            Level = 20,
                            MagicArmor = 0,
                            MagicAtack = 0,
                            Name = "Shield Of The Damned",
                            Price = 50,
                            Profession = 0,
                            SpriteURL = "secondaryWarrior20.gif",
                            Weight = 6
                        },
                        new
                        {
                            Id = 10,
                            Armor = 0,
                            Atack = 25,
                            CriticalChance = 5,
                            ItemType = 1,
                            Level = 20,
                            MagicArmor = 0,
                            MagicAtack = 0,
                            Name = "Poisoned Arrow",
                            Price = 20,
                            Profession = 1,
                            SpriteURL = "secondaryHunter20.gif",
                            Weight = 1
                        },
                        new
                        {
                            Id = 11,
                            Armor = 0,
                            Atack = 0,
                            CriticalChance = 2,
                            ItemType = 1,
                            Level = 20,
                            MagicArmor = 0,
                            MagicAtack = 50,
                            Name = "The Sorcerer's Book",
                            Price = 100,
                            Profession = 2,
                            SpriteURL = "secondaryMage20.gif",
                            Weight = 3
                        },
                        new
                        {
                            Id = 12,
                            Armor = 25,
                            Atack = 0,
                            CriticalChance = 3,
                            ItemType = 1,
                            Level = 20,
                            MagicArmor = 25,
                            MagicAtack = 0,
                            Name = "Shield Of The Order",
                            Price = 75,
                            Profession = 3,
                            SpriteURL = "secondaryPaladin20.gif",
                            Weight = 6
                        });
                });

            modelBuilder.Entity("Classes.Models.Game.Item.Weapon.DBWeapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Atack")
                        .HasColumnType("int");

                    b.Property<int>("CriticalChance")
                        .HasColumnType("int");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MagicAtack")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Profession")
                        .HasColumnType("int");

                    b.Property<string>("SpriteURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Weapons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Atack = 20,
                            CriticalChance = 0,
                            ItemType = 0,
                            Level = 1,
                            MagicAtack = 0,
                            Name = "Beginner's Sword",
                            Price = 10,
                            Profession = 0,
                            SpriteURL = "primaryWarrior0.gif",
                            Weight = 5
                        },
                        new
                        {
                            Id = 2,
                            Atack = 10,
                            CriticalChance = 0,
                            ItemType = 0,
                            Level = 1,
                            MagicAtack = 0,
                            Name = "Slingshot",
                            Price = 10,
                            Profession = 1,
                            SpriteURL = "primaryHunter0.gif",
                            Weight = 3
                        },
                        new
                        {
                            Id = 3,
                            Atack = 0,
                            CriticalChance = 0,
                            ItemType = 0,
                            Level = 1,
                            MagicAtack = 15,
                            Name = "Beginner's Staff",
                            Price = 10,
                            Profession = 2,
                            SpriteURL = "primaryMage0.gif",
                            Weight = 4
                        },
                        new
                        {
                            Id = 4,
                            Atack = 15,
                            CriticalChance = 0,
                            ItemType = 0,
                            Level = 1,
                            MagicAtack = 5,
                            Name = "Blunt Sword",
                            Price = 10,
                            Profession = 3,
                            SpriteURL = "primaryPaladin0.gif",
                            Weight = 5
                        },
                        new
                        {
                            Id = 5,
                            Atack = 40,
                            CriticalChance = 0,
                            ItemType = 0,
                            Level = 10,
                            MagicAtack = 0,
                            Name = "Sword Of Glory",
                            Price = 50,
                            Profession = 0,
                            SpriteURL = "primaryWarrior10.gif",
                            Weight = 7
                        },
                        new
                        {
                            Id = 6,
                            Atack = 25,
                            CriticalChance = 5,
                            ItemType = 0,
                            Level = 10,
                            MagicAtack = 0,
                            Name = "Recurve Bow",
                            Price = 50,
                            Profession = 1,
                            SpriteURL = "primaryHunter10.gif",
                            Weight = 4
                        },
                        new
                        {
                            Id = 7,
                            Atack = 0,
                            CriticalChance = 2,
                            ItemType = 0,
                            Level = 10,
                            MagicAtack = 30,
                            Name = "Staff of Serpents",
                            Price = 50,
                            Profession = 2,
                            SpriteURL = "primaryMage10.gif",
                            Weight = 5
                        },
                        new
                        {
                            Id = 8,
                            Atack = 30,
                            CriticalChance = 0,
                            ItemType = 0,
                            Level = 10,
                            MagicAtack = 15,
                            Name = "Broad sword",
                            Price = 50,
                            Profession = 3,
                            SpriteURL = "primaryPaladin10.gif",
                            Weight = 8
                        },
                        new
                        {
                            Id = 9,
                            Atack = 80,
                            CriticalChance = 2,
                            ItemType = 0,
                            Level = 20,
                            MagicAtack = 0,
                            Name = "Victors' Saber",
                            Price = 150,
                            Profession = 0,
                            SpriteURL = "primaryWarrior20.gif",
                            Weight = 8
                        },
                        new
                        {
                            Id = 10,
                            Atack = 55,
                            CriticalChance = 10,
                            ItemType = 0,
                            Level = 20,
                            MagicAtack = 0,
                            Name = "Orc Bow",
                            Price = 150,
                            Profession = 1,
                            SpriteURL = "primaryHunter20.gif",
                            Weight = 5
                        },
                        new
                        {
                            Id = 11,
                            Atack = 0,
                            CriticalChance = 5,
                            ItemType = 0,
                            Level = 20,
                            MagicAtack = 60,
                            Name = "Staff of the Woods",
                            Price = 150,
                            Profession = 2,
                            SpriteURL = "primaryMage20.gif",
                            Weight = 7
                        },
                        new
                        {
                            Id = 12,
                            Atack = 70,
                            CriticalChance = 5,
                            ItemType = 0,
                            Level = 20,
                            MagicAtack = 5,
                            Name = "Upgraded Broad sword",
                            Price = 150,
                            Profession = 3,
                            SpriteURL = "primaryPaladin20.gif",
                            Weight = 9
                        },
                        new
                        {
                            Id = 13,
                            Atack = 120,
                            CriticalChance = 5,
                            ItemType = 0,
                            Level = 30,
                            MagicAtack = 0,
                            Name = "Sword Of Darkness",
                            Price = 350,
                            Profession = 0,
                            SpriteURL = "primaryWarrior30.gif",
                            Weight = 8
                        },
                        new
                        {
                            Id = 14,
                            Atack = 70,
                            CriticalChance = 15,
                            ItemType = 0,
                            Level = 30,
                            MagicAtack = 0,
                            Name = "Bow Of Darkness",
                            Price = 350,
                            Profession = 1,
                            SpriteURL = "primaryHunter30.gif",
                            Weight = 6
                        },
                        new
                        {
                            Id = 15,
                            Atack = 0,
                            CriticalChance = 5,
                            ItemType = 0,
                            Level = 30,
                            MagicAtack = 90,
                            Name = "Staff of the Order",
                            Price = 350,
                            Profession = 2,
                            SpriteURL = "primaryMage30.gif",
                            Weight = 7
                        },
                        new
                        {
                            Id = 16,
                            Atack = 110,
                            CriticalChance = 0,
                            ItemType = 0,
                            Level = 30,
                            MagicAtack = 40,
                            Name = "Sword of the Order",
                            Price = 350,
                            Profession = 3,
                            SpriteURL = "primaryPaladin30.gif",
                            Weight = 8
                        });
                });

            modelBuilder.Entity("Classes.Models.User.DBUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c4593731-59d3-411a-a2f3-8f312d50b744",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "9ce37f33-96e9-49e6-95d4-9a11303fa477",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = "8a8278a3-78a0-405d-9d0f-d6444d78e4c4",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Classes.Models.Game.Hero.DBHero", b =>
                {
                    b.HasOne("Classes.Models.Game.Item.Armor.DBArmor", "DBArmor")
                        .WithMany("Heroes")
                        .HasForeignKey("ArmorId");

                    b.HasOne("Classes.Models.Game.Item.Boots.DBBoots", "DBBoots")
                        .WithMany("Heroes")
                        .HasForeignKey("BootsId");

                    b.HasOne("Classes.Models.Game.Item.Gloves.DBGloves", "DBGloves")
                        .WithMany("Heroes")
                        .HasForeignKey("GlovesId");

                    b.HasOne("Classes.Models.Game.Item.Helmet.DBHelmet", "DBHelmet")
                        .WithMany("Heroes")
                        .HasForeignKey("HelmetId");

                    b.HasOne("Classes.Models.Game.Item.Necklace.DBNecklace", "DBNecklace")
                        .WithMany("Heroes")
                        .HasForeignKey("NecklaceId");

                    b.HasOne("Classes.Models.Game.Item.Ring.DBRing", "DBRing")
                        .WithMany("Heroes")
                        .HasForeignKey("RingId");

                    b.HasOne("Classes.Models.Game.Item.SecondaryWeapon.DBSecondaryWeapon", "DBSecondaryWeapon")
                        .WithMany("Heroes")
                        .HasForeignKey("SecondaryWeaponId");

                    b.HasOne("Classes.Models.User.DBUser", "DBUser")
                        .WithMany("Heroes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Classes.Models.Game.Item.Weapon.DBWeapon", "DBWeapon")
                        .WithMany("Heroes")
                        .HasForeignKey("WeaponId");

                    b.Navigation("DBArmor");

                    b.Navigation("DBBoots");

                    b.Navigation("DBGloves");

                    b.Navigation("DBHelmet");

                    b.Navigation("DBNecklace");

                    b.Navigation("DBRing");

                    b.Navigation("DBSecondaryWeapon");

                    b.Navigation("DBUser");

                    b.Navigation("DBWeapon");
                });

            modelBuilder.Entity("Classes.Models.Game.Hero.DBHeroEquipment", b =>
                {
                    b.HasOne("Classes.Models.Game.Hero.DBHero", "DBHero")
                        .WithMany("HeroEquipment")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DBHero");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Classes.Models.User.DBUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Classes.Models.User.DBUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Classes.Models.User.DBUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Classes.Models.User.DBUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Classes.Models.Game.Hero.DBHero", b =>
                {
                    b.Navigation("HeroEquipment");
                });

            modelBuilder.Entity("Classes.Models.Game.Item.Armor.DBArmor", b =>
                {
                    b.Navigation("Heroes");
                });

            modelBuilder.Entity("Classes.Models.Game.Item.Boots.DBBoots", b =>
                {
                    b.Navigation("Heroes");
                });

            modelBuilder.Entity("Classes.Models.Game.Item.Gloves.DBGloves", b =>
                {
                    b.Navigation("Heroes");
                });

            modelBuilder.Entity("Classes.Models.Game.Item.Helmet.DBHelmet", b =>
                {
                    b.Navigation("Heroes");
                });

            modelBuilder.Entity("Classes.Models.Game.Item.Necklace.DBNecklace", b =>
                {
                    b.Navigation("Heroes");
                });

            modelBuilder.Entity("Classes.Models.Game.Item.Ring.DBRing", b =>
                {
                    b.Navigation("Heroes");
                });

            modelBuilder.Entity("Classes.Models.Game.Item.SecondaryWeapon.DBSecondaryWeapon", b =>
                {
                    b.Navigation("Heroes");
                });

            modelBuilder.Entity("Classes.Models.Game.Item.Weapon.DBWeapon", b =>
                {
                    b.Navigation("Heroes");
                });

            modelBuilder.Entity("Classes.Models.User.DBUser", b =>
                {
                    b.Navigation("Heroes");
                });
#pragma warning restore 612, 618
        }
    }
}
